### ISSUE TITLE
R version discrepancy

### ISSUE THREAD

**Issue by topepo** [renozao/rngtools#3]
The GH repo has 

 * the R version requirement as : R (≥ **3.3.0**), methods, pkgmaker (≥ 0.20)

whereas  CRAN  has it as 

* R (≥ **3.6.0**), methods, pkgmaker (≥ 0.20)

Since there are also different versions of the package (1.3.1 on GH and 1.3.1.1 on CRAN), I'm guessing  that a CRAN maintainer **revised your package and bumped the version**. I see no public mention of the reason. 

Can you submit a new version that lowers the version requirement? This affects `NMF` and now that package's dependencies only work for R-devel.

**Comment by romainfrancois** [comment]
See https://github.com/cran/rngtools/commit/c9c036b18e0bf6f20afcab15a2b38083aaf62da7 for the changes of the 1.3.1.1 version

**Comment by pkfsantos** [comment]
I need the rngtools version 1.3 for R version 3.5. How could I do that? Some of you could help me?

**Comment by topepo** [comment]
[Here](https://cran.r-project.org/src/contrib/Archive/rngtools/) for the sources. You'd have to build it.

**Comment by JorisChau** [comment]
This also affects the `projpred` package, which now fails to install from CRAN for R < 3.6.0

**Comment by topepo** [comment]
Fixes are in #4

**Comment by topepo** [comment]
CRAN  has refused to take (another) modified version of the package to reduce the version requirement and the maintainer is AWOL. The message that I got was

>> Max: I’m not the maintainer, so I won't get the email. 
>
> CRAN: Ah, I misunderstood entirely! 
>CRAN: This is about submitting another maintainer'sa package? 
>
>CRAN: This is not possible. In case the other maintainer does not respond, 
>CRAN: simply szbmit your package again, we will accept it and finally ask the 
>CRAN: other maintainer to fix the other package or it will be archived. 

It looks like we'll have to work around BDR's fumbling on this.

**Comment by renozao** [comment]
Apologies on the delay. I’ll try get the push request to CRAN this week.

**Comment by topepo** [comment]
That would be great! There's a PR that fixes it in #4

**Comment by topepo** [comment]
Any progress on this? I have to do a `recipes` submission this week and a new version of `rngtools` would impact that (in a good way).

**Comment by renozao** [comment]
I am working on it.
The change in the RNGkind input and output have more implications than just the unit test. They imply relatively simple fixes, yet in multiple places and side effects need to be checked carefully.

**Comment by renozao** [comment]
This issue has now been fixed in 188c4d9
Version 1.4.0 is on its way to CRAN. Please allow some time for it to make it to the repos.
Thank you for your patience and thanks to @topepo for the kickoff PR!

**Comment by topepo** [comment]
This is great! Thanks for doing this.
